CREATE TABLE id(
  NAME  CHAR(24),
  Badgenumber  CHAR(24));

INSERT INTO id
  (NAME,Badgenumber)
VALUES('BARENG, KENNETH ANGELO','2');

INSERT INTO id
  (NAME,Badgenumber)
VALUES('BARENG, KAREN ANGELINE','3');

